//
//  LoggingHelper.h
//  ReadLet
//
//  Created by Nagendra on 5/28/19.
//  Copyright © 2019 Rely Labs. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface LoggingHelper : NSObject
+ (void) initLogsAnalyticsProvider;
+ (void) reportLogsDataToAnalytics:(NSString *)event_name;


// app activity events
#define APP_BG @"APP_BG"
#define APP_FG @"APP_FG"

// get started events
#define SCREEN_GET_STARTED_VISIBLE @"SCREEN_GET_STARTED_VISIBLE"
#define CLICKED_GET_STARTED @"CLICKED_GET_STARTED"

// Phone no add events
#define SCREEN_PHONE_NO_ASK_VISIBLE @"SCREEN_PHONE_NO_ASK_VISIBLE"
#define TYPING_PHONE_NO @"TYPING_PHONE_NO"
#define CHANGED_PHONE_NO @"CHANGED_PHONE_NO"

#define PHONE_SEND_SERVER_SUCCESS @"PHONE_SEND_SERVER_SUCCESS"
#define PHONE_SEND_SERVER_FAILED @"PHONE_SEND_SERVER_FAILED"

// otp screen
#define SCREEN_OTP_ADD_VISIBLE @"SCREEN_OTP_ADD_VISIBLE"
#define TYPING_OTP @"TYPING_OTP"
#define CLICKED_RESEND_OTP @"CLICKED_RESEND_OTP"
#define OTP_SEND_SERVER_SUCCESS @"OTP_SEND_SERVER_SUCCESS"
#define OTP_SEND_SERVER_FAILED @"OTP_SEND_SERVER_FAILED"
#define CLICKED_RESEND_OTP_SERVER_SUCCESS @"CLICKED_RESEND_OTP_SERVER_SUCCESS"
#define CLICKED_RESEND_OTP_SERVER_FAILED @"CLICKED_RESEND_OTP_SERVER_FAILED"

// name ask screen
#define SCREEN_NAME_ASK_VISIBLE @"SCREEN_NAME_ASK_VISIBLE"
#define TYPING_NAME @"TYPING_NAME"
#define NAME_SEND_BUTTON_ENABLED @"NAME_SEND_BUTTON_ENABLED"
#define CLICKED_NAME_SEND @"CLICKED_NAME_SEND"
#define NAME_SEND_SERVER_SUCCESS @"NAME_SEND_SERVER_SUCCESS"
#define NAME_SEND_SERVER_FAILED @"NAME_SEND_SERVER_FAILED"

#define TAP_ARTICLE @"TAP_ARTICLE"
#define RENDER_WEBVIEW @"RENDER_WEBVIEW"
#define BACK_WEBVIEW @"BACK_WEBVIEW"
#define CLOSE_WEBVIEW @"CLOSE_WEBVIEW"
#define RENDER_WEBVIEW_SUCCESS @"RENDER_WEBVIEW_SUCCESS"

@end

NS_ASSUME_NONNULL_END
